# a very minimal declarative config file
_format_version: "2.1"
_transform: true

services:
  - name: tweet-service
    url: http://localhost:8084
    routes:
      - name: tweet-service-routes
        paths:
          - /
        strip_path: true

